# Generated by Django 3.2.8 on 2021-11-05 14:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20211031_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('posted_on', models.DateField(default=django.utils.timezone.now)),
                ('star', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tutor')),
            ],
        ),
    ]
