# Generated by Django 3.2.6 on 2021-11-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile2_suxx5z.png', null=True, upload_to='static/users/profile'),
        ),
    ]
