# Generated by Django 3.2.6 on 2021-11-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='https://cloudinary.com/console/c-26da7dea9ecf685e231c3a2d4c7239/media_library/folders/be8d774ced8966ff8127954b5ada19c202/asset/b8651dd82b635e5470445359a9abc6fc/manage', null=True, upload_to='static/users/profile'),
        ),
    ]
